spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlin
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
jwt:
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}
  secretKey: ${JWT_SECRET}
  accessExpiration: ${JWT_ACCESS_EXP:3600}
  refreshExpiration: ${JWT_REFRESH_EXP:3600}